name = "tony-laine-app"
type = "javascript"
account_id = "58eeea88c91135f3236db74f1cddacbc"
workers_dev = true
compatibility_date = "2025-01-01"

# Add CLAUDE_API_KEY and JWT_SECRET via environment variables
